// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileMetadata.proto

package proto;

public final class FileMetadata {
  private FileMetadata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileMetadataDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.FileMetadataDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool fileInfoAvailable = 1;</code>
     * @return The fileInfoAvailable.
     */
    boolean getFileInfoAvailable();

    /**
     * <code>bool packetInfoAvailable = 2;</code>
     * @return The packetInfoAvailable.
     */
    boolean getPacketInfoAvailable();

    /**
     * <code>string fileName = 3;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 3;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    long getFileSize();

    /**
     * <code>bytes checksum = 5;</code>
     * @return The checksum.
     */
    com.google.protobuf.ByteString getChecksum();

    /**
     * <code>uint64 totalNumberOfPackets = 6;</code>
     * @return The totalNumberOfPackets.
     */
    long getTotalNumberOfPackets();

    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @return A list containing the swarmMemberInfo.
     */
    java.util.List<com.google.protobuf.ByteString> getSwarmMemberInfoList();
    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @return The count of swarmMemberInfo.
     */
    int getSwarmMemberInfoCount();
    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @param index The index of the element to return.
     * @return The swarmMemberInfo at the given index.
     */
    com.google.protobuf.ByteString getSwarmMemberInfo(int index);
  }
  /**
   * Protobuf type {@code tutorial.FileMetadataDetails}
   */
  public static final class FileMetadataDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.FileMetadataDetails)
      FileMetadataDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileMetadataDetails.newBuilder() to construct.
    private FileMetadataDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileMetadataDetails() {
      fileName_ = "";
      checksum_ = com.google.protobuf.ByteString.EMPTY;
      swarmMemberInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileMetadataDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileMetadataDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fileInfoAvailable_ = input.readBool();
              break;
            }
            case 16: {

              packetInfoAvailable_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 32: {

              fileSize_ = input.readUInt64();
              break;
            }
            case 42: {

              checksum_ = input.readBytes();
              break;
            }
            case 48: {

              totalNumberOfPackets_ = input.readUInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                swarmMemberInfo_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              swarmMemberInfo_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          swarmMemberInfo_ = java.util.Collections.unmodifiableList(swarmMemberInfo_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.FileMetadata.internal_static_tutorial_FileMetadataDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.FileMetadata.internal_static_tutorial_FileMetadataDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FileMetadata.FileMetadataDetails.class, proto.FileMetadata.FileMetadataDetails.Builder.class);
    }

    public static final int FILEINFOAVAILABLE_FIELD_NUMBER = 1;
    private boolean fileInfoAvailable_;
    /**
     * <code>bool fileInfoAvailable = 1;</code>
     * @return The fileInfoAvailable.
     */
    @java.lang.Override
    public boolean getFileInfoAvailable() {
      return fileInfoAvailable_;
    }

    public static final int PACKETINFOAVAILABLE_FIELD_NUMBER = 2;
    private boolean packetInfoAvailable_;
    /**
     * <code>bool packetInfoAvailable = 2;</code>
     * @return The packetInfoAvailable.
     */
    @java.lang.Override
    public boolean getPacketInfoAvailable() {
      return packetInfoAvailable_;
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 3;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 3;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESIZE_FIELD_NUMBER = 4;
    private long fileSize_;
    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString checksum_;
    /**
     * <code>bytes checksum = 5;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChecksum() {
      return checksum_;
    }

    public static final int TOTALNUMBEROFPACKETS_FIELD_NUMBER = 6;
    private long totalNumberOfPackets_;
    /**
     * <code>uint64 totalNumberOfPackets = 6;</code>
     * @return The totalNumberOfPackets.
     */
    @java.lang.Override
    public long getTotalNumberOfPackets() {
      return totalNumberOfPackets_;
    }

    public static final int SWARMMEMBERINFO_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> swarmMemberInfo_;
    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @return A list containing the swarmMemberInfo.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getSwarmMemberInfoList() {
      return swarmMemberInfo_;
    }
    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @return The count of swarmMemberInfo.
     */
    public int getSwarmMemberInfoCount() {
      return swarmMemberInfo_.size();
    }
    /**
     * <code>repeated bytes swarmMemberInfo = 7;</code>
     * @param index The index of the element to return.
     * @return The swarmMemberInfo at the given index.
     */
    public com.google.protobuf.ByteString getSwarmMemberInfo(int index) {
      return swarmMemberInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fileInfoAvailable_ != false) {
        output.writeBool(1, fileInfoAvailable_);
      }
      if (packetInfoAvailable_ != false) {
        output.writeBool(2, packetInfoAvailable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      if (fileSize_ != 0L) {
        output.writeUInt64(4, fileSize_);
      }
      if (!checksum_.isEmpty()) {
        output.writeBytes(5, checksum_);
      }
      if (totalNumberOfPackets_ != 0L) {
        output.writeUInt64(6, totalNumberOfPackets_);
      }
      for (int i = 0; i < swarmMemberInfo_.size(); i++) {
        output.writeBytes(7, swarmMemberInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fileInfoAvailable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, fileInfoAvailable_);
      }
      if (packetInfoAvailable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, packetInfoAvailable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fileSize_);
      }
      if (!checksum_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, checksum_);
      }
      if (totalNumberOfPackets_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, totalNumberOfPackets_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < swarmMemberInfo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(swarmMemberInfo_.get(i));
        }
        size += dataSize;
        size += 1 * getSwarmMemberInfoList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.FileMetadata.FileMetadataDetails)) {
        return super.equals(obj);
      }
      proto.FileMetadata.FileMetadataDetails other = (proto.FileMetadata.FileMetadataDetails) obj;

      if (getFileInfoAvailable()
          != other.getFileInfoAvailable()) return false;
      if (getPacketInfoAvailable()
          != other.getPacketInfoAvailable()) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getFileSize()
          != other.getFileSize()) return false;
      if (!getChecksum()
          .equals(other.getChecksum())) return false;
      if (getTotalNumberOfPackets()
          != other.getTotalNumberOfPackets()) return false;
      if (!getSwarmMemberInfoList()
          .equals(other.getSwarmMemberInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILEINFOAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFileInfoAvailable());
      hash = (37 * hash) + PACKETINFOAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPacketInfoAvailable());
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSize());
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (37 * hash) + TOTALNUMBEROFPACKETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalNumberOfPackets());
      if (getSwarmMemberInfoCount() > 0) {
        hash = (37 * hash) + SWARMMEMBERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getSwarmMemberInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FileMetadata.FileMetadataDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.FileMetadata.FileMetadataDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FileMetadata.FileMetadataDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.FileMetadata.FileMetadataDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.FileMetadataDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.FileMetadataDetails)
        proto.FileMetadata.FileMetadataDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.FileMetadata.internal_static_tutorial_FileMetadataDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.FileMetadata.internal_static_tutorial_FileMetadataDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.FileMetadata.FileMetadataDetails.class, proto.FileMetadata.FileMetadataDetails.Builder.class);
      }

      // Construct using proto.FileMetadata.FileMetadataDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileInfoAvailable_ = false;

        packetInfoAvailable_ = false;

        fileName_ = "";

        fileSize_ = 0L;

        checksum_ = com.google.protobuf.ByteString.EMPTY;

        totalNumberOfPackets_ = 0L;

        swarmMemberInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.FileMetadata.internal_static_tutorial_FileMetadataDetails_descriptor;
      }

      @java.lang.Override
      public proto.FileMetadata.FileMetadataDetails getDefaultInstanceForType() {
        return proto.FileMetadata.FileMetadataDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.FileMetadata.FileMetadataDetails build() {
        proto.FileMetadata.FileMetadataDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.FileMetadata.FileMetadataDetails buildPartial() {
        proto.FileMetadata.FileMetadataDetails result = new proto.FileMetadata.FileMetadataDetails(this);
        int from_bitField0_ = bitField0_;
        result.fileInfoAvailable_ = fileInfoAvailable_;
        result.packetInfoAvailable_ = packetInfoAvailable_;
        result.fileName_ = fileName_;
        result.fileSize_ = fileSize_;
        result.checksum_ = checksum_;
        result.totalNumberOfPackets_ = totalNumberOfPackets_;
        if (((bitField0_ & 0x00000001) != 0)) {
          swarmMemberInfo_ = java.util.Collections.unmodifiableList(swarmMemberInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.swarmMemberInfo_ = swarmMemberInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.FileMetadata.FileMetadataDetails) {
          return mergeFrom((proto.FileMetadata.FileMetadataDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.FileMetadata.FileMetadataDetails other) {
        if (other == proto.FileMetadata.FileMetadataDetails.getDefaultInstance()) return this;
        if (other.getFileInfoAvailable() != false) {
          setFileInfoAvailable(other.getFileInfoAvailable());
        }
        if (other.getPacketInfoAvailable() != false) {
          setPacketInfoAvailable(other.getPacketInfoAvailable());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        if (other.getChecksum() != com.google.protobuf.ByteString.EMPTY) {
          setChecksum(other.getChecksum());
        }
        if (other.getTotalNumberOfPackets() != 0L) {
          setTotalNumberOfPackets(other.getTotalNumberOfPackets());
        }
        if (!other.swarmMemberInfo_.isEmpty()) {
          if (swarmMemberInfo_.isEmpty()) {
            swarmMemberInfo_ = other.swarmMemberInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSwarmMemberInfoIsMutable();
            swarmMemberInfo_.addAll(other.swarmMemberInfo_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.FileMetadata.FileMetadataDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.FileMetadata.FileMetadataDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean fileInfoAvailable_ ;
      /**
       * <code>bool fileInfoAvailable = 1;</code>
       * @return The fileInfoAvailable.
       */
      @java.lang.Override
      public boolean getFileInfoAvailable() {
        return fileInfoAvailable_;
      }
      /**
       * <code>bool fileInfoAvailable = 1;</code>
       * @param value The fileInfoAvailable to set.
       * @return This builder for chaining.
       */
      public Builder setFileInfoAvailable(boolean value) {
        
        fileInfoAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool fileInfoAvailable = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileInfoAvailable() {
        
        fileInfoAvailable_ = false;
        onChanged();
        return this;
      }

      private boolean packetInfoAvailable_ ;
      /**
       * <code>bool packetInfoAvailable = 2;</code>
       * @return The packetInfoAvailable.
       */
      @java.lang.Override
      public boolean getPacketInfoAvailable() {
        return packetInfoAvailable_;
      }
      /**
       * <code>bool packetInfoAvailable = 2;</code>
       * @param value The packetInfoAvailable to set.
       * @return This builder for chaining.
       */
      public Builder setPacketInfoAvailable(boolean value) {
        
        packetInfoAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool packetInfoAvailable = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketInfoAvailable() {
        
        packetInfoAvailable_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 3;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return The fileSize.
       */
      @java.lang.Override
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(long value) {
        
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {
        
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString checksum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes checksum = 5;</code>
       * @return The checksum.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChecksum() {
        return checksum_;
      }
      /**
       * <code>bytes checksum = 5;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes checksum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }

      private long totalNumberOfPackets_ ;
      /**
       * <code>uint64 totalNumberOfPackets = 6;</code>
       * @return The totalNumberOfPackets.
       */
      @java.lang.Override
      public long getTotalNumberOfPackets() {
        return totalNumberOfPackets_;
      }
      /**
       * <code>uint64 totalNumberOfPackets = 6;</code>
       * @param value The totalNumberOfPackets to set.
       * @return This builder for chaining.
       */
      public Builder setTotalNumberOfPackets(long value) {
        
        totalNumberOfPackets_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 totalNumberOfPackets = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalNumberOfPackets() {
        
        totalNumberOfPackets_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> swarmMemberInfo_ = java.util.Collections.emptyList();
      private void ensureSwarmMemberInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          swarmMemberInfo_ = new java.util.ArrayList<com.google.protobuf.ByteString>(swarmMemberInfo_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @return A list containing the swarmMemberInfo.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSwarmMemberInfoList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(swarmMemberInfo_) : swarmMemberInfo_;
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @return The count of swarmMemberInfo.
       */
      public int getSwarmMemberInfoCount() {
        return swarmMemberInfo_.size();
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @param index The index of the element to return.
       * @return The swarmMemberInfo at the given index.
       */
      public com.google.protobuf.ByteString getSwarmMemberInfo(int index) {
        return swarmMemberInfo_.get(index);
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @param index The index to set the value at.
       * @param value The swarmMemberInfo to set.
       * @return This builder for chaining.
       */
      public Builder setSwarmMemberInfo(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSwarmMemberInfoIsMutable();
        swarmMemberInfo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @param value The swarmMemberInfo to add.
       * @return This builder for chaining.
       */
      public Builder addSwarmMemberInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSwarmMemberInfoIsMutable();
        swarmMemberInfo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @param values The swarmMemberInfo to add.
       * @return This builder for chaining.
       */
      public Builder addAllSwarmMemberInfo(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSwarmMemberInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, swarmMemberInfo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes swarmMemberInfo = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSwarmMemberInfo() {
        swarmMemberInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.FileMetadataDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.FileMetadataDetails)
    private static final proto.FileMetadata.FileMetadataDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.FileMetadata.FileMetadataDetails();
    }

    public static proto.FileMetadata.FileMetadataDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileMetadataDetails>
        PARSER = new com.google.protobuf.AbstractParser<FileMetadataDetails>() {
      @java.lang.Override
      public FileMetadataDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileMetadataDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileMetadataDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileMetadataDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.FileMetadata.FileMetadataDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_FileMetadataDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_FileMetadataDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022FileMetadata.proto\022\010tutorial\"\272\001\n\023FileM" +
      "etadataDetails\022\031\n\021fileInfoAvailable\030\001 \001(" +
      "\010\022\033\n\023packetInfoAvailable\030\002 \001(\010\022\020\n\010fileNa" +
      "me\030\003 \001(\t\022\020\n\010fileSize\030\004 \001(\004\022\020\n\010checksum\030\005" +
      " \001(\014\022\034\n\024totalNumberOfPackets\030\006 \001(\004\022\027\n\017sw" +
      "armMemberInfo\030\007 \003(\014B\025\n\005protoB\014FileMetada" +
      "tab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_FileMetadataDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_FileMetadataDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_FileMetadataDetails_descriptor,
        new java.lang.String[] { "FileInfoAvailable", "PacketInfoAvailable", "FileName", "FileSize", "Checksum", "TotalNumberOfPackets", "SwarmMemberInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
