// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitialMessage.proto

package proto;

public final class InitialMessage {
  private InitialMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InitialMessageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.InitialMessageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();

    /**
     * <code>string peerIp = 2;</code>
     * @return The peerIp.
     */
    java.lang.String getPeerIp();
    /**
     * <code>string peerIp = 2;</code>
     * @return The bytes for peerIp.
     */
    com.google.protobuf.ByteString
        getPeerIpBytes();

    /**
     * <code>uint32 peerPort = 3;</code>
     * @return The peerPort.
     */
    int getPeerPort();

    /**
     * <code>string fileToDownload = 4;</code>
     * @return The fileToDownload.
     */
    java.lang.String getFileToDownload();
    /**
     * <code>string fileToDownload = 4;</code>
     * @return The bytes for fileToDownload.
     */
    com.google.protobuf.ByteString
        getFileToDownloadBytes();
  }
  /**
   * Protobuf type {@code tutorial.InitialMessageDetails}
   */
  public static final class InitialMessageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.InitialMessageDetails)
      InitialMessageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InitialMessageDetails.newBuilder() to construct.
    private InitialMessageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitialMessageDetails() {
      peerName_ = "";
      peerIp_ = "";
      fileToDownload_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InitialMessageDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InitialMessageDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              peerName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              peerIp_ = s;
              break;
            }
            case 24: {

              peerPort_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fileToDownload_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.InitialMessage.internal_static_tutorial_InitialMessageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.InitialMessage.internal_static_tutorial_InitialMessageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.InitialMessage.InitialMessageDetails.class, proto.InitialMessage.InitialMessageDetails.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object peerName_;
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEERIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object peerIp_;
    /**
     * <code>string peerIp = 2;</code>
     * @return The peerIp.
     */
    @java.lang.Override
    public java.lang.String getPeerIp() {
      java.lang.Object ref = peerIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerIp_ = s;
        return s;
      }
    }
    /**
     * <code>string peerIp = 2;</code>
     * @return The bytes for peerIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerIpBytes() {
      java.lang.Object ref = peerIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEERPORT_FIELD_NUMBER = 3;
    private int peerPort_;
    /**
     * <code>uint32 peerPort = 3;</code>
     * @return The peerPort.
     */
    @java.lang.Override
    public int getPeerPort() {
      return peerPort_;
    }

    public static final int FILETODOWNLOAD_FIELD_NUMBER = 4;
    private volatile java.lang.Object fileToDownload_;
    /**
     * <code>string fileToDownload = 4;</code>
     * @return The fileToDownload.
     */
    @java.lang.Override
    public java.lang.String getFileToDownload() {
      java.lang.Object ref = fileToDownload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileToDownload_ = s;
        return s;
      }
    }
    /**
     * <code>string fileToDownload = 4;</code>
     * @return The bytes for fileToDownload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileToDownloadBytes() {
      java.lang.Object ref = fileToDownload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileToDownload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, peerName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, peerIp_);
      }
      if (peerPort_ != 0) {
        output.writeUInt32(3, peerPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToDownload_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileToDownload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, peerName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, peerIp_);
      }
      if (peerPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, peerPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToDownload_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileToDownload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.InitialMessage.InitialMessageDetails)) {
        return super.equals(obj);
      }
      proto.InitialMessage.InitialMessageDetails other = (proto.InitialMessage.InitialMessageDetails) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getPeerIp()
          .equals(other.getPeerIp())) return false;
      if (getPeerPort()
          != other.getPeerPort()) return false;
      if (!getFileToDownload()
          .equals(other.getFileToDownload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (37 * hash) + PEERIP_FIELD_NUMBER;
      hash = (53 * hash) + getPeerIp().hashCode();
      hash = (37 * hash) + PEERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getPeerPort();
      hash = (37 * hash) + FILETODOWNLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getFileToDownload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.InitialMessage.InitialMessageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.InitialMessage.InitialMessageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.InitialMessage.InitialMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.InitialMessage.InitialMessageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.InitialMessageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.InitialMessageDetails)
        proto.InitialMessage.InitialMessageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.InitialMessage.internal_static_tutorial_InitialMessageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.InitialMessage.internal_static_tutorial_InitialMessageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.InitialMessage.InitialMessageDetails.class, proto.InitialMessage.InitialMessageDetails.Builder.class);
      }

      // Construct using proto.InitialMessage.InitialMessageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        peerName_ = "";

        peerIp_ = "";

        peerPort_ = 0;

        fileToDownload_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.InitialMessage.internal_static_tutorial_InitialMessageDetails_descriptor;
      }

      @java.lang.Override
      public proto.InitialMessage.InitialMessageDetails getDefaultInstanceForType() {
        return proto.InitialMessage.InitialMessageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.InitialMessage.InitialMessageDetails build() {
        proto.InitialMessage.InitialMessageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.InitialMessage.InitialMessageDetails buildPartial() {
        proto.InitialMessage.InitialMessageDetails result = new proto.InitialMessage.InitialMessageDetails(this);
        result.peerName_ = peerName_;
        result.peerIp_ = peerIp_;
        result.peerPort_ = peerPort_;
        result.fileToDownload_ = fileToDownload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.InitialMessage.InitialMessageDetails) {
          return mergeFrom((proto.InitialMessage.InitialMessageDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.InitialMessage.InitialMessageDetails other) {
        if (other == proto.InitialMessage.InitialMessageDetails.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          onChanged();
        }
        if (!other.getPeerIp().isEmpty()) {
          peerIp_ = other.peerIp_;
          onChanged();
        }
        if (other.getPeerPort() != 0) {
          setPeerPort(other.getPeerPort());
        }
        if (!other.getFileToDownload().isEmpty()) {
          fileToDownload_ = other.fileToDownload_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.InitialMessage.InitialMessageDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.InitialMessage.InitialMessageDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        
        peerName_ = getDefaultInstance().getPeerName();
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object peerIp_ = "";
      /**
       * <code>string peerIp = 2;</code>
       * @return The peerIp.
       */
      public java.lang.String getPeerIp() {
        java.lang.Object ref = peerIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerIp = 2;</code>
       * @return The bytes for peerIp.
       */
      public com.google.protobuf.ByteString
          getPeerIpBytes() {
        java.lang.Object ref = peerIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerIp = 2;</code>
       * @param value The peerIp to set.
       * @return This builder for chaining.
       */
      public Builder setPeerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string peerIp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerIp() {
        
        peerIp_ = getDefaultInstance().getPeerIp();
        onChanged();
        return this;
      }
      /**
       * <code>string peerIp = 2;</code>
       * @param value The bytes for peerIp to set.
       * @return This builder for chaining.
       */
      public Builder setPeerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peerIp_ = value;
        onChanged();
        return this;
      }

      private int peerPort_ ;
      /**
       * <code>uint32 peerPort = 3;</code>
       * @return The peerPort.
       */
      @java.lang.Override
      public int getPeerPort() {
        return peerPort_;
      }
      /**
       * <code>uint32 peerPort = 3;</code>
       * @param value The peerPort to set.
       * @return This builder for chaining.
       */
      public Builder setPeerPort(int value) {
        
        peerPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 peerPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerPort() {
        
        peerPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileToDownload_ = "";
      /**
       * <code>string fileToDownload = 4;</code>
       * @return The fileToDownload.
       */
      public java.lang.String getFileToDownload() {
        java.lang.Object ref = fileToDownload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileToDownload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileToDownload = 4;</code>
       * @return The bytes for fileToDownload.
       */
      public com.google.protobuf.ByteString
          getFileToDownloadBytes() {
        java.lang.Object ref = fileToDownload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileToDownload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileToDownload = 4;</code>
       * @param value The fileToDownload to set.
       * @return This builder for chaining.
       */
      public Builder setFileToDownload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileToDownload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileToDownload = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileToDownload() {
        
        fileToDownload_ = getDefaultInstance().getFileToDownload();
        onChanged();
        return this;
      }
      /**
       * <code>string fileToDownload = 4;</code>
       * @param value The bytes for fileToDownload to set.
       * @return This builder for chaining.
       */
      public Builder setFileToDownloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileToDownload_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.InitialMessageDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.InitialMessageDetails)
    private static final proto.InitialMessage.InitialMessageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.InitialMessage.InitialMessageDetails();
    }

    public static proto.InitialMessage.InitialMessageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitialMessageDetails>
        PARSER = new com.google.protobuf.AbstractParser<InitialMessageDetails>() {
      @java.lang.Override
      public InitialMessageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitialMessageDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitialMessageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InitialMessageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.InitialMessage.InitialMessageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_InitialMessageDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_InitialMessageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024InitialMessage.proto\022\010tutorial\"c\n\025Init" +
      "ialMessageDetails\022\020\n\010peerName\030\001 \001(\t\022\016\n\006p" +
      "eerIp\030\002 \001(\t\022\020\n\010peerPort\030\003 \001(\r\022\026\n\016fileToD" +
      "ownload\030\004 \001(\tB\027\n\005protoB\016InitialMessageb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_InitialMessageDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_InitialMessageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_InitialMessageDetails_descriptor,
        new java.lang.String[] { "PeerName", "PeerIp", "PeerPort", "FileToDownload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
