// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitialSetupDoneAck.proto

package proto;

public final class InitialSetupDoneAck {
  private InitialSetupDoneAck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InitialSetupDoneAckDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.InitialSetupDoneAckDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool successful = 1;</code>
     * @return The successful.
     */
    boolean getSuccessful();

    /**
     * <code>string fileToDownload = 2;</code>
     * @return The fileToDownload.
     */
    java.lang.String getFileToDownload();
    /**
     * <code>string fileToDownload = 2;</code>
     * @return The bytes for fileToDownload.
     */
    com.google.protobuf.ByteString
        getFileToDownloadBytes();
  }
  /**
   * Protobuf type {@code tutorial.InitialSetupDoneAckDetail}
   */
  public static final class InitialSetupDoneAckDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.InitialSetupDoneAckDetail)
      InitialSetupDoneAckDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InitialSetupDoneAckDetail.newBuilder() to construct.
    private InitialSetupDoneAckDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitialSetupDoneAckDetail() {
      fileToDownload_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InitialSetupDoneAckDetail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InitialSetupDoneAckDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              successful_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileToDownload_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.InitialSetupDoneAck.internal_static_tutorial_InitialSetupDoneAckDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.InitialSetupDoneAck.internal_static_tutorial_InitialSetupDoneAckDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.class, proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.Builder.class);
    }

    public static final int SUCCESSFUL_FIELD_NUMBER = 1;
    private boolean successful_;
    /**
     * <code>bool successful = 1;</code>
     * @return The successful.
     */
    @java.lang.Override
    public boolean getSuccessful() {
      return successful_;
    }

    public static final int FILETODOWNLOAD_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileToDownload_;
    /**
     * <code>string fileToDownload = 2;</code>
     * @return The fileToDownload.
     */
    @java.lang.Override
    public java.lang.String getFileToDownload() {
      java.lang.Object ref = fileToDownload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileToDownload_ = s;
        return s;
      }
    }
    /**
     * <code>string fileToDownload = 2;</code>
     * @return The bytes for fileToDownload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileToDownloadBytes() {
      java.lang.Object ref = fileToDownload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileToDownload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (successful_ != false) {
        output.writeBool(1, successful_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToDownload_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileToDownload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (successful_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, successful_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToDownload_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileToDownload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.InitialSetupDoneAck.InitialSetupDoneAckDetail)) {
        return super.equals(obj);
      }
      proto.InitialSetupDoneAck.InitialSetupDoneAckDetail other = (proto.InitialSetupDoneAck.InitialSetupDoneAckDetail) obj;

      if (getSuccessful()
          != other.getSuccessful()) return false;
      if (!getFileToDownload()
          .equals(other.getFileToDownload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESSFUL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccessful());
      hash = (37 * hash) + FILETODOWNLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getFileToDownload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.InitialSetupDoneAck.InitialSetupDoneAckDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.InitialSetupDoneAckDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.InitialSetupDoneAckDetail)
        proto.InitialSetupDoneAck.InitialSetupDoneAckDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.InitialSetupDoneAck.internal_static_tutorial_InitialSetupDoneAckDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.InitialSetupDoneAck.internal_static_tutorial_InitialSetupDoneAckDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.class, proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.Builder.class);
      }

      // Construct using proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        successful_ = false;

        fileToDownload_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.InitialSetupDoneAck.internal_static_tutorial_InitialSetupDoneAckDetail_descriptor;
      }

      @java.lang.Override
      public proto.InitialSetupDoneAck.InitialSetupDoneAckDetail getDefaultInstanceForType() {
        return proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.getDefaultInstance();
      }

      @java.lang.Override
      public proto.InitialSetupDoneAck.InitialSetupDoneAckDetail build() {
        proto.InitialSetupDoneAck.InitialSetupDoneAckDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.InitialSetupDoneAck.InitialSetupDoneAckDetail buildPartial() {
        proto.InitialSetupDoneAck.InitialSetupDoneAckDetail result = new proto.InitialSetupDoneAck.InitialSetupDoneAckDetail(this);
        result.successful_ = successful_;
        result.fileToDownload_ = fileToDownload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.InitialSetupDoneAck.InitialSetupDoneAckDetail) {
          return mergeFrom((proto.InitialSetupDoneAck.InitialSetupDoneAckDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.InitialSetupDoneAck.InitialSetupDoneAckDetail other) {
        if (other == proto.InitialSetupDoneAck.InitialSetupDoneAckDetail.getDefaultInstance()) return this;
        if (other.getSuccessful() != false) {
          setSuccessful(other.getSuccessful());
        }
        if (!other.getFileToDownload().isEmpty()) {
          fileToDownload_ = other.fileToDownload_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.InitialSetupDoneAck.InitialSetupDoneAckDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.InitialSetupDoneAck.InitialSetupDoneAckDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean successful_ ;
      /**
       * <code>bool successful = 1;</code>
       * @return The successful.
       */
      @java.lang.Override
      public boolean getSuccessful() {
        return successful_;
      }
      /**
       * <code>bool successful = 1;</code>
       * @param value The successful to set.
       * @return This builder for chaining.
       */
      public Builder setSuccessful(boolean value) {
        
        successful_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool successful = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccessful() {
        
        successful_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object fileToDownload_ = "";
      /**
       * <code>string fileToDownload = 2;</code>
       * @return The fileToDownload.
       */
      public java.lang.String getFileToDownload() {
        java.lang.Object ref = fileToDownload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileToDownload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileToDownload = 2;</code>
       * @return The bytes for fileToDownload.
       */
      public com.google.protobuf.ByteString
          getFileToDownloadBytes() {
        java.lang.Object ref = fileToDownload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileToDownload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileToDownload = 2;</code>
       * @param value The fileToDownload to set.
       * @return This builder for chaining.
       */
      public Builder setFileToDownload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileToDownload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileToDownload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileToDownload() {
        
        fileToDownload_ = getDefaultInstance().getFileToDownload();
        onChanged();
        return this;
      }
      /**
       * <code>string fileToDownload = 2;</code>
       * @param value The bytes for fileToDownload to set.
       * @return This builder for chaining.
       */
      public Builder setFileToDownloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileToDownload_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.InitialSetupDoneAckDetail)
    }

    // @@protoc_insertion_point(class_scope:tutorial.InitialSetupDoneAckDetail)
    private static final proto.InitialSetupDoneAck.InitialSetupDoneAckDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.InitialSetupDoneAck.InitialSetupDoneAckDetail();
    }

    public static proto.InitialSetupDoneAck.InitialSetupDoneAckDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitialSetupDoneAckDetail>
        PARSER = new com.google.protobuf.AbstractParser<InitialSetupDoneAckDetail>() {
      @java.lang.Override
      public InitialSetupDoneAckDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitialSetupDoneAckDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitialSetupDoneAckDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InitialSetupDoneAckDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.InitialSetupDoneAck.InitialSetupDoneAckDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_InitialSetupDoneAckDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_InitialSetupDoneAckDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031InitialSetupDoneAck.proto\022\010tutorial\"G\n" +
      "\031InitialSetupDoneAckDetail\022\022\n\nsuccessful" +
      "\030\001 \001(\010\022\026\n\016fileToDownload\030\002 \001(\tB\034\n\005protoB" +
      "\023InitialSetupDoneAckb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_InitialSetupDoneAckDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_InitialSetupDoneAckDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_InitialSetupDoneAckDetail_descriptor,
        new java.lang.String[] { "Successful", "FileToDownload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
