// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterMessage.proto

package proto;

public final class RegisterMessage {
  private RegisterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterMessageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.RegisterMessageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string senderName = 1;</code>
     * @return The senderName.
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 1;</code>
     * @return The bytes for senderName.
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string senderIp = 2;</code>
     * @return The senderIp.
     */
    java.lang.String getSenderIp();
    /**
     * <code>string senderIp = 2;</code>
     * @return The bytes for senderIp.
     */
    com.google.protobuf.ByteString
        getSenderIpBytes();

    /**
     * <code>uint32 senderPort = 3;</code>
     * @return The senderPort.
     */
    int getSenderPort();

    /**
     * <code>uint64 numberOfFilesAvailable = 4;</code>
     * @return The numberOfFilesAvailable.
     */
    long getNumberOfFilesAvailable();

    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @return A list containing the fileInfo.
     */
    java.util.List<com.google.protobuf.ByteString> getFileInfoList();
    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @return The count of fileInfo.
     */
    int getFileInfoCount();
    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @param index The index of the element to return.
     * @return The fileInfo at the given index.
     */
    com.google.protobuf.ByteString getFileInfo(int index);
  }
  /**
   * Protobuf type {@code tutorial.RegisterMessageDetails}
   */
  public static final class RegisterMessageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.RegisterMessageDetails)
      RegisterMessageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterMessageDetails.newBuilder() to construct.
    private RegisterMessageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterMessageDetails() {
      senderName_ = "";
      senderIp_ = "";
      fileInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisterMessageDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterMessageDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderIp_ = s;
              break;
            }
            case 24: {

              senderPort_ = input.readUInt32();
              break;
            }
            case 32: {

              numberOfFilesAvailable_ = input.readUInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fileInfo_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              fileInfo_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          fileInfo_ = java.util.Collections.unmodifiableList(fileInfo_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RegisterMessage.internal_static_tutorial_RegisterMessageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RegisterMessage.internal_static_tutorial_RegisterMessageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RegisterMessage.RegisterMessageDetails.class, proto.RegisterMessage.RegisterMessageDetails.Builder.class);
    }

    public static final int SENDERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 1;</code>
     * @return The senderName.
     */
    @java.lang.Override
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 1;</code>
     * @return The bytes for senderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderIp_;
    /**
     * <code>string senderIp = 2;</code>
     * @return The senderIp.
     */
    @java.lang.Override
    public java.lang.String getSenderIp() {
      java.lang.Object ref = senderIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderIp_ = s;
        return s;
      }
    }
    /**
     * <code>string senderIp = 2;</code>
     * @return The bytes for senderIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderIpBytes() {
      java.lang.Object ref = senderIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPORT_FIELD_NUMBER = 3;
    private int senderPort_;
    /**
     * <code>uint32 senderPort = 3;</code>
     * @return The senderPort.
     */
    @java.lang.Override
    public int getSenderPort() {
      return senderPort_;
    }

    public static final int NUMBEROFFILESAVAILABLE_FIELD_NUMBER = 4;
    private long numberOfFilesAvailable_;
    /**
     * <code>uint64 numberOfFilesAvailable = 4;</code>
     * @return The numberOfFilesAvailable.
     */
    @java.lang.Override
    public long getNumberOfFilesAvailable() {
      return numberOfFilesAvailable_;
    }

    public static final int FILEINFO_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> fileInfo_;
    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @return A list containing the fileInfo.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getFileInfoList() {
      return fileInfo_;
    }
    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @return The count of fileInfo.
     */
    public int getFileInfoCount() {
      return fileInfo_.size();
    }
    /**
     * <code>repeated bytes fileInfo = 5;</code>
     * @param index The index of the element to return.
     * @return The fileInfo at the given index.
     */
    public com.google.protobuf.ByteString getFileInfo(int index) {
      return fileInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderIp_);
      }
      if (senderPort_ != 0) {
        output.writeUInt32(3, senderPort_);
      }
      if (numberOfFilesAvailable_ != 0L) {
        output.writeUInt64(4, numberOfFilesAvailable_);
      }
      for (int i = 0; i < fileInfo_.size(); i++) {
        output.writeBytes(5, fileInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderIp_);
      }
      if (senderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, senderPort_);
      }
      if (numberOfFilesAvailable_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, numberOfFilesAvailable_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fileInfo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fileInfo_.get(i));
        }
        size += dataSize;
        size += 1 * getFileInfoList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RegisterMessage.RegisterMessageDetails)) {
        return super.equals(obj);
      }
      proto.RegisterMessage.RegisterMessageDetails other = (proto.RegisterMessage.RegisterMessageDetails) obj;

      if (!getSenderName()
          .equals(other.getSenderName())) return false;
      if (!getSenderIp()
          .equals(other.getSenderIp())) return false;
      if (getSenderPort()
          != other.getSenderPort()) return false;
      if (getNumberOfFilesAvailable()
          != other.getNumberOfFilesAvailable()) return false;
      if (!getFileInfoList()
          .equals(other.getFileInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + SENDERIP_FIELD_NUMBER;
      hash = (53 * hash) + getSenderIp().hashCode();
      hash = (37 * hash) + SENDERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPort();
      hash = (37 * hash) + NUMBEROFFILESAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumberOfFilesAvailable());
      if (getFileInfoCount() > 0) {
        hash = (37 * hash) + FILEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getFileInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RegisterMessage.RegisterMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RegisterMessage.RegisterMessageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RegisterMessageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.RegisterMessageDetails)
        proto.RegisterMessage.RegisterMessageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RegisterMessage.internal_static_tutorial_RegisterMessageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RegisterMessage.internal_static_tutorial_RegisterMessageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RegisterMessage.RegisterMessageDetails.class, proto.RegisterMessage.RegisterMessageDetails.Builder.class);
      }

      // Construct using proto.RegisterMessage.RegisterMessageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderName_ = "";

        senderIp_ = "";

        senderPort_ = 0;

        numberOfFilesAvailable_ = 0L;

        fileInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RegisterMessage.internal_static_tutorial_RegisterMessageDetails_descriptor;
      }

      @java.lang.Override
      public proto.RegisterMessage.RegisterMessageDetails getDefaultInstanceForType() {
        return proto.RegisterMessage.RegisterMessageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RegisterMessage.RegisterMessageDetails build() {
        proto.RegisterMessage.RegisterMessageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RegisterMessage.RegisterMessageDetails buildPartial() {
        proto.RegisterMessage.RegisterMessageDetails result = new proto.RegisterMessage.RegisterMessageDetails(this);
        int from_bitField0_ = bitField0_;
        result.senderName_ = senderName_;
        result.senderIp_ = senderIp_;
        result.senderPort_ = senderPort_;
        result.numberOfFilesAvailable_ = numberOfFilesAvailable_;
        if (((bitField0_ & 0x00000001) != 0)) {
          fileInfo_ = java.util.Collections.unmodifiableList(fileInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fileInfo_ = fileInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RegisterMessage.RegisterMessageDetails) {
          return mergeFrom((proto.RegisterMessage.RegisterMessageDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RegisterMessage.RegisterMessageDetails other) {
        if (other == proto.RegisterMessage.RegisterMessageDetails.getDefaultInstance()) return this;
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getSenderIp().isEmpty()) {
          senderIp_ = other.senderIp_;
          onChanged();
        }
        if (other.getSenderPort() != 0) {
          setSenderPort(other.getSenderPort());
        }
        if (other.getNumberOfFilesAvailable() != 0L) {
          setNumberOfFilesAvailable(other.getNumberOfFilesAvailable());
        }
        if (!other.fileInfo_.isEmpty()) {
          if (fileInfo_.isEmpty()) {
            fileInfo_ = other.fileInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFileInfoIsMutable();
            fileInfo_.addAll(other.fileInfo_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RegisterMessage.RegisterMessageDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RegisterMessage.RegisterMessageDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 1;</code>
       * @return The senderName.
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 1;</code>
       * @return The bytes for senderName.
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 1;</code>
       * @param value The senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 1;</code>
       * @param value The bytes for senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderIp_ = "";
      /**
       * <code>string senderIp = 2;</code>
       * @return The senderIp.
       */
      public java.lang.String getSenderIp() {
        java.lang.Object ref = senderIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderIp = 2;</code>
       * @return The bytes for senderIp.
       */
      public com.google.protobuf.ByteString
          getSenderIpBytes() {
        java.lang.Object ref = senderIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderIp = 2;</code>
       * @param value The senderIp to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderIp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderIp() {
        
        senderIp_ = getDefaultInstance().getSenderIp();
        onChanged();
        return this;
      }
      /**
       * <code>string senderIp = 2;</code>
       * @param value The bytes for senderIp to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderIp_ = value;
        onChanged();
        return this;
      }

      private int senderPort_ ;
      /**
       * <code>uint32 senderPort = 3;</code>
       * @return The senderPort.
       */
      @java.lang.Override
      public int getSenderPort() {
        return senderPort_;
      }
      /**
       * <code>uint32 senderPort = 3;</code>
       * @param value The senderPort to set.
       * @return This builder for chaining.
       */
      public Builder setSenderPort(int value) {
        
        senderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 senderPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderPort() {
        
        senderPort_ = 0;
        onChanged();
        return this;
      }

      private long numberOfFilesAvailable_ ;
      /**
       * <code>uint64 numberOfFilesAvailable = 4;</code>
       * @return The numberOfFilesAvailable.
       */
      @java.lang.Override
      public long getNumberOfFilesAvailable() {
        return numberOfFilesAvailable_;
      }
      /**
       * <code>uint64 numberOfFilesAvailable = 4;</code>
       * @param value The numberOfFilesAvailable to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfFilesAvailable(long value) {
        
        numberOfFilesAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 numberOfFilesAvailable = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfFilesAvailable() {
        
        numberOfFilesAvailable_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> fileInfo_ = java.util.Collections.emptyList();
      private void ensureFileInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fileInfo_ = new java.util.ArrayList<com.google.protobuf.ByteString>(fileInfo_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @return A list containing the fileInfo.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getFileInfoList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(fileInfo_) : fileInfo_;
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @return The count of fileInfo.
       */
      public int getFileInfoCount() {
        return fileInfo_.size();
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @param index The index of the element to return.
       * @return The fileInfo at the given index.
       */
      public com.google.protobuf.ByteString getFileInfo(int index) {
        return fileInfo_.get(index);
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @param index The index to set the value at.
       * @param value The fileInfo to set.
       * @return This builder for chaining.
       */
      public Builder setFileInfo(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFileInfoIsMutable();
        fileInfo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @param value The fileInfo to add.
       * @return This builder for chaining.
       */
      public Builder addFileInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFileInfoIsMutable();
        fileInfo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @param values The fileInfo to add.
       * @return This builder for chaining.
       */
      public Builder addAllFileInfo(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFileInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileInfo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes fileInfo = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileInfo() {
        fileInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.RegisterMessageDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.RegisterMessageDetails)
    private static final proto.RegisterMessage.RegisterMessageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RegisterMessage.RegisterMessageDetails();
    }

    public static proto.RegisterMessage.RegisterMessageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterMessageDetails>
        PARSER = new com.google.protobuf.AbstractParser<RegisterMessageDetails>() {
      @java.lang.Override
      public RegisterMessageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterMessageDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterMessageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterMessageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RegisterMessage.RegisterMessageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RegisterMessageDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_RegisterMessageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RegisterMessage.proto\022\010tutorial\"\204\001\n\026Re" +
      "gisterMessageDetails\022\022\n\nsenderName\030\001 \001(\t" +
      "\022\020\n\010senderIp\030\002 \001(\t\022\022\n\nsenderPort\030\003 \001(\r\022\036" +
      "\n\026numberOfFilesAvailable\030\004 \001(\004\022\020\n\010fileIn" +
      "fo\030\005 \003(\014B\030\n\005protoB\017RegisterMessageb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_RegisterMessageDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_RegisterMessageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_RegisterMessageDetails_descriptor,
        new java.lang.String[] { "SenderName", "SenderIp", "SenderPort", "NumberOfFilesAvailable", "FileInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
