// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetupForFileMessage.proto

package proto;

public final class SetupForFileMessage {
  private SetupForFileMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SetupForFileMessageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.SetupForFileMessageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string senderName = 1;</code>
     * @return The senderName.
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 1;</code>
     * @return The bytes for senderName.
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string senderIp = 2;</code>
     * @return The senderIp.
     */
    java.lang.String getSenderIp();
    /**
     * <code>string senderIp = 2;</code>
     * @return The bytes for senderIp.
     */
    com.google.protobuf.ByteString
        getSenderIpBytes();

    /**
     * <code>uint32 senderPort = 3;</code>
     * @return The senderPort.
     */
    int getSenderPort();

    /**
     * <code>string fileToBeDownloaded = 4;</code>
     * @return The fileToBeDownloaded.
     */
    java.lang.String getFileToBeDownloaded();
    /**
     * <code>string fileToBeDownloaded = 4;</code>
     * @return The bytes for fileToBeDownloaded.
     */
    com.google.protobuf.ByteString
        getFileToBeDownloadedBytes();
  }
  /**
   * Protobuf type {@code tutorial.SetupForFileMessageDetails}
   */
  public static final class SetupForFileMessageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.SetupForFileMessageDetails)
      SetupForFileMessageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetupForFileMessageDetails.newBuilder() to construct.
    private SetupForFileMessageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetupForFileMessageDetails() {
      senderName_ = "";
      senderIp_ = "";
      fileToBeDownloaded_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SetupForFileMessageDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetupForFileMessageDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderIp_ = s;
              break;
            }
            case 24: {

              senderPort_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fileToBeDownloaded_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SetupForFileMessage.internal_static_tutorial_SetupForFileMessageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SetupForFileMessage.internal_static_tutorial_SetupForFileMessageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SetupForFileMessage.SetupForFileMessageDetails.class, proto.SetupForFileMessage.SetupForFileMessageDetails.Builder.class);
    }

    public static final int SENDERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 1;</code>
     * @return The senderName.
     */
    @java.lang.Override
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 1;</code>
     * @return The bytes for senderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderIp_;
    /**
     * <code>string senderIp = 2;</code>
     * @return The senderIp.
     */
    @java.lang.Override
    public java.lang.String getSenderIp() {
      java.lang.Object ref = senderIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderIp_ = s;
        return s;
      }
    }
    /**
     * <code>string senderIp = 2;</code>
     * @return The bytes for senderIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderIpBytes() {
      java.lang.Object ref = senderIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPORT_FIELD_NUMBER = 3;
    private int senderPort_;
    /**
     * <code>uint32 senderPort = 3;</code>
     * @return The senderPort.
     */
    @java.lang.Override
    public int getSenderPort() {
      return senderPort_;
    }

    public static final int FILETOBEDOWNLOADED_FIELD_NUMBER = 4;
    private volatile java.lang.Object fileToBeDownloaded_;
    /**
     * <code>string fileToBeDownloaded = 4;</code>
     * @return The fileToBeDownloaded.
     */
    @java.lang.Override
    public java.lang.String getFileToBeDownloaded() {
      java.lang.Object ref = fileToBeDownloaded_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileToBeDownloaded_ = s;
        return s;
      }
    }
    /**
     * <code>string fileToBeDownloaded = 4;</code>
     * @return The bytes for fileToBeDownloaded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileToBeDownloadedBytes() {
      java.lang.Object ref = fileToBeDownloaded_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileToBeDownloaded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderIp_);
      }
      if (senderPort_ != 0) {
        output.writeUInt32(3, senderPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToBeDownloaded_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileToBeDownloaded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderIp_);
      }
      if (senderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, senderPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileToBeDownloaded_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileToBeDownloaded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SetupForFileMessage.SetupForFileMessageDetails)) {
        return super.equals(obj);
      }
      proto.SetupForFileMessage.SetupForFileMessageDetails other = (proto.SetupForFileMessage.SetupForFileMessageDetails) obj;

      if (!getSenderName()
          .equals(other.getSenderName())) return false;
      if (!getSenderIp()
          .equals(other.getSenderIp())) return false;
      if (getSenderPort()
          != other.getSenderPort()) return false;
      if (!getFileToBeDownloaded()
          .equals(other.getFileToBeDownloaded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + SENDERIP_FIELD_NUMBER;
      hash = (53 * hash) + getSenderIp().hashCode();
      hash = (37 * hash) + SENDERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPort();
      hash = (37 * hash) + FILETOBEDOWNLOADED_FIELD_NUMBER;
      hash = (53 * hash) + getFileToBeDownloaded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SetupForFileMessage.SetupForFileMessageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SetupForFileMessage.SetupForFileMessageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SetupForFileMessageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.SetupForFileMessageDetails)
        proto.SetupForFileMessage.SetupForFileMessageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SetupForFileMessage.internal_static_tutorial_SetupForFileMessageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SetupForFileMessage.internal_static_tutorial_SetupForFileMessageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SetupForFileMessage.SetupForFileMessageDetails.class, proto.SetupForFileMessage.SetupForFileMessageDetails.Builder.class);
      }

      // Construct using proto.SetupForFileMessage.SetupForFileMessageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderName_ = "";

        senderIp_ = "";

        senderPort_ = 0;

        fileToBeDownloaded_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SetupForFileMessage.internal_static_tutorial_SetupForFileMessageDetails_descriptor;
      }

      @java.lang.Override
      public proto.SetupForFileMessage.SetupForFileMessageDetails getDefaultInstanceForType() {
        return proto.SetupForFileMessage.SetupForFileMessageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.SetupForFileMessage.SetupForFileMessageDetails build() {
        proto.SetupForFileMessage.SetupForFileMessageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.SetupForFileMessage.SetupForFileMessageDetails buildPartial() {
        proto.SetupForFileMessage.SetupForFileMessageDetails result = new proto.SetupForFileMessage.SetupForFileMessageDetails(this);
        result.senderName_ = senderName_;
        result.senderIp_ = senderIp_;
        result.senderPort_ = senderPort_;
        result.fileToBeDownloaded_ = fileToBeDownloaded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SetupForFileMessage.SetupForFileMessageDetails) {
          return mergeFrom((proto.SetupForFileMessage.SetupForFileMessageDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SetupForFileMessage.SetupForFileMessageDetails other) {
        if (other == proto.SetupForFileMessage.SetupForFileMessageDetails.getDefaultInstance()) return this;
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getSenderIp().isEmpty()) {
          senderIp_ = other.senderIp_;
          onChanged();
        }
        if (other.getSenderPort() != 0) {
          setSenderPort(other.getSenderPort());
        }
        if (!other.getFileToBeDownloaded().isEmpty()) {
          fileToBeDownloaded_ = other.fileToBeDownloaded_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SetupForFileMessage.SetupForFileMessageDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SetupForFileMessage.SetupForFileMessageDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 1;</code>
       * @return The senderName.
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 1;</code>
       * @return The bytes for senderName.
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 1;</code>
       * @param value The senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 1;</code>
       * @param value The bytes for senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderIp_ = "";
      /**
       * <code>string senderIp = 2;</code>
       * @return The senderIp.
       */
      public java.lang.String getSenderIp() {
        java.lang.Object ref = senderIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderIp = 2;</code>
       * @return The bytes for senderIp.
       */
      public com.google.protobuf.ByteString
          getSenderIpBytes() {
        java.lang.Object ref = senderIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderIp = 2;</code>
       * @param value The senderIp to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderIp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderIp() {
        
        senderIp_ = getDefaultInstance().getSenderIp();
        onChanged();
        return this;
      }
      /**
       * <code>string senderIp = 2;</code>
       * @param value The bytes for senderIp to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderIp_ = value;
        onChanged();
        return this;
      }

      private int senderPort_ ;
      /**
       * <code>uint32 senderPort = 3;</code>
       * @return The senderPort.
       */
      @java.lang.Override
      public int getSenderPort() {
        return senderPort_;
      }
      /**
       * <code>uint32 senderPort = 3;</code>
       * @param value The senderPort to set.
       * @return This builder for chaining.
       */
      public Builder setSenderPort(int value) {
        
        senderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 senderPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderPort() {
        
        senderPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileToBeDownloaded_ = "";
      /**
       * <code>string fileToBeDownloaded = 4;</code>
       * @return The fileToBeDownloaded.
       */
      public java.lang.String getFileToBeDownloaded() {
        java.lang.Object ref = fileToBeDownloaded_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileToBeDownloaded_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileToBeDownloaded = 4;</code>
       * @return The bytes for fileToBeDownloaded.
       */
      public com.google.protobuf.ByteString
          getFileToBeDownloadedBytes() {
        java.lang.Object ref = fileToBeDownloaded_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileToBeDownloaded_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileToBeDownloaded = 4;</code>
       * @param value The fileToBeDownloaded to set.
       * @return This builder for chaining.
       */
      public Builder setFileToBeDownloaded(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileToBeDownloaded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileToBeDownloaded = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileToBeDownloaded() {
        
        fileToBeDownloaded_ = getDefaultInstance().getFileToBeDownloaded();
        onChanged();
        return this;
      }
      /**
       * <code>string fileToBeDownloaded = 4;</code>
       * @param value The bytes for fileToBeDownloaded to set.
       * @return This builder for chaining.
       */
      public Builder setFileToBeDownloadedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileToBeDownloaded_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.SetupForFileMessageDetails)
    }

    // @@protoc_insertion_point(class_scope:tutorial.SetupForFileMessageDetails)
    private static final proto.SetupForFileMessage.SetupForFileMessageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SetupForFileMessage.SetupForFileMessageDetails();
    }

    public static proto.SetupForFileMessage.SetupForFileMessageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetupForFileMessageDetails>
        PARSER = new com.google.protobuf.AbstractParser<SetupForFileMessageDetails>() {
      @java.lang.Override
      public SetupForFileMessageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetupForFileMessageDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetupForFileMessageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetupForFileMessageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.SetupForFileMessage.SetupForFileMessageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SetupForFileMessageDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SetupForFileMessageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SetupForFileMessage.proto\022\010tutorial\"r\n" +
      "\032SetupForFileMessageDetails\022\022\n\nsenderNam" +
      "e\030\001 \001(\t\022\020\n\010senderIp\030\002 \001(\t\022\022\n\nsenderPort\030" +
      "\003 \001(\r\022\032\n\022fileToBeDownloaded\030\004 \001(\tB\034\n\005pro" +
      "toB\023SetupForFileMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_SetupForFileMessageDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_SetupForFileMessageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SetupForFileMessageDetails_descriptor,
        new java.lang.String[] { "SenderName", "SenderIp", "SenderPort", "FileToBeDownloaded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
